### ISSUE TITLE
ISSN 1573-0697 | Journal of Business Ethics | Rezension Review Paper

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1028]
Das Review Paper ist ebenfalls eine Rezension. Dieser Artikel müsste das Tag 655 bekommen:
https://link.springer.com/article/10.1007/s10551-018-4066-0

**Comment by kdr154** [comment]
Noch nicht getagt:

![grafik](https://user-images.githubusercontent.com/29707105/87425083-5869e280-c5dd-11ea-8391-b8addce3fb97.png)

**Comment by socheres** [comment]
mit "Try Url" getestet

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_ktwk58" "--output-filename=nzyrgW.xml"  "--config-overrides=zotero_review_regex       = "(^Review of)\|(^Book  Reviews?)" remove_marc_field_650a    = "^Book Reviews?$""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://link.springer.com/article/10.1007/s10551-018-4066-0"  "Journal of business ethics"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of business ethics' \| DIRECT @ https://link.springer.com/article/10.1007/s10551-018-4066-0 set download-delay for domain 'link.springer.com' to 1000 ms   Harvesting URL 1 [Journal of business ...] \| https://link.springer.com/article/10.1007/s10551-018-4066-0 {9342975384940834645} Harvest successful     Converting item 1 [Journal of business ...] \| https://link.springer.com/article/10.1007/s10551-018-4066-0 {9342975384940834645} use online ISSN "1573-0697" with online PPN "270937129" post-processed author first name = 'Roger Leonard', last name = 'Burritt', title = '', affix = '' post-processed author first name = 'Katherine Leanne', last name = 'Christ', title = '', affix = '' post-processed author first name = 'Hussain Gulzar', last name = 'Rammal', title = '', affix = '' post-processed author first name = 'Stefan', last name = 'Schaltegger', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1007/s10551-018-4066-0, 	item_type: review, 	title: Multinational Enterprise Strategies for Addressing Sustainability: the Need for Consolidation, 	short_title: Multinational Enterprise Strategies for Addressing Sustainability, 	abstract_note: This paper examines the growing number of publications on multinational enterprise management of sustainability issues. Based on an integrative literature review and thematic analysis, the paper analyses and synthesises the current state of knowledge about main issues arising. Key issues identified include the following: choice of sustainability strategies; management of the views of headquarters towards sustainability; local cultural sustainability perspectives in developed and developing host countries; MNEs with home in developing/emerging countries; and resource availability for implementing sustainability initiatives. Findings indicate that although the literature is tending towards growing acceptance about sustainability and its challenges most researchers have focused on corporate social responsibility and investigate their own niche problem, industry, and country, using their own chosen theory and do not consider the need for consolidation and integration of social, environmental and economic performance. Avenues for future research are identified which will provide a means for the ethical foundations of theory and practice to be improved., 	publication_title: Journal of business ethics, 	volume: 164, 	issue: 2, 	pages: 389-410, 	date: 2020-06-01, 	doi: 10.1007/s10551-018-4066-0, 	language: eng, 	issn: 1573-0697, 	superior_ppn: 270937129, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Roger Leonard, 			last_name: Burritt, 			type: author, 		}, 		{ 			first_name: Katherine Leanne, 			last_name: Christ, 			type: author, 		}, 		{ 			first_name: Hussain Gulzar, 			last_name: Rammal, 			type: author, 		}, 		{ 			first_name: Stefan, 			last_name: Schaltegger, 			type: author, 		}, 	], 	keywords: [ Multinational enterprise, Sustainability strategy, Distance, Book Reviews ], } erased field '650a' due to removal filter '^Book Reviews?$' Generated record with hash '1F8BC1D51A569FFF888D0F44B3FDDC0B78877DDA'  Conversion complete   Generated 1 record(s) for item 1 [Journal of business ...] \| https://link.springer.com/article/10.1007/s10551-018-4066-0 {9342975384940834645}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
