### ISSUE TITLE
ISSN 1478-1913 | The Muslim World | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1034]
**URL**
https://onlinelibrary.wiley.com/toc/14781913/2020/110/2

**Ausführliche Problembeschreibung**
Die 4 Rezensionen werden nicht in 655 getagt.
Erhalten stattdessen:
<datafield tag="650" ind1=" " ind2="4"><subfield code="a">Book Review, Book Review</subfield></datafield>

**Offenbare Lösungen**
passende Regex in conf erstellen

**Comment by socheres** [comment]
mit "Try URL" getestet.

use online ISSN "1478-1913" with online PPN "341340766"
post-processed author first name = 'Najib George', last name = 'Awad', title = '', affix = ''
added GND number 1014622271 for author Awad, Najib George (SWB lookup)
keyword matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12330,
	item_type: review,
	title: Sacred Misinterpretation: Reaching Across the Christian-Muslim Divide By Martin Accad, Grand Rapids, Mich: W.B. Eerdmans Publishing Company, 2019, pp. 346, ISBN 978-0-8028-7414-6,
	short_title: Sacred Misinterpretation,
	publication_title: The Muslim World,
	volume: 110,
	issue: 2,
	pages: 259-262,
	date: 2020-01-01,
	doi: 10.1111/muwo.12330,
	language: eng,
	issn: 1478-1913,
	superior_ppn: 341340766,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: Najib George,
			last_name: Awad,
			type: author,
			gnd_number: 1014622271,
		},
	],
	keywords: [ Book Review, Book Review ],
}
erased field '650a' due to removal filter '^Book Reviews?'
Generated record with hash '0275AFC498A6978F06839194D2943D517E70FBCE'

use online ISSN "1478-1913" with online PPN "341340766"
post-processed author first name = 'Kambiz', last name = 'GhaneaBassiri', title = '', affix = ''
added GND number 142237175 for author GhaneaBassiri, Kambiz (SWB lookup)
keyword matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12333,
	item_type: review,
	title: Speaking Quran: An American Scripture. By Timur R. Yuskaev, Columbia: University of South Carolina Press, 2017. ISBN 978-1-61117-794-7 Hardcover, $44.99,
	short_title: Speaking Quran,
	publication_title: The Muslim World,
	volume: 110,
	issue: 2,
	pages: 263-264,
	date: 2020-01-01,
	doi: 10.1111/muwo.12333,
	language: eng,
	issn: 1478-1913,
	superior_ppn: 341340766,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: Kambiz,
			last_name: GhaneaBassiri,
			type: author,
			gnd_number: 142237175,
		},
	],
	keywords: [ Book Review, Book Review ],
}
erased field '650a' due to removal filter '^Book Reviews?'
Generated record with hash '5876CCAD152EB2C331A2BDEF349156A67B05C63D'

use online ISSN "1478-1913" with online PPN "341340766"
post-processed author first name = 'David D.', last name = 'Grafton', title = '', affix = ''
keyword matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12332,
	item_type: review,
	title: The Community of Believers: Christian and Muslim Perspectives. By Lucinda Mosher and David Marshall eds. Washington D.C.: Georgetown University Press, 2015, 171 pp., $26.95 (paperback), ISBN 978-1-62616-196-2,
	short_title: The Community of Believers,
	publication_title: The Muslim World,
	volume: 110,
	issue: 2,
	pages: 265-266,
	date: 2020-01-01,
	doi: 10.1111/muwo.12332,
	language: eng,
	issn: 1478-1913,
	superior_ppn: 341340766,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: David D.,
			last_name: Grafton,
			type: author,
		},
	],
	keywords: [ Book Review, Book Review ],
}
erased field '650a' due to removal filter '^Book Reviews?'
Generated record with hash 'D474672780D5B0AB643BF4665BC5C9C5CE16D268'

use online ISSN "1478-1913" with online PPN "341340766"
post-processed author first name = 'David D.', last name = 'Grafton', title = '', affix = ''
keyword matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12331,
	item_type: review,
	title: The Political Lives of Saints: Christian-Muslim Mediation in Egypt. By Angie Heo, Oakland, CA: University of California Press, 2018. Pb. 294 pages.,
	short_title: The Political Lives of Saints,
	publication_title: The Muslim World,
	volume: 110,
	issue: 2,
	pages: 267-269,
	date: 2020-01-01,
	doi: 10.1111/muwo.12331,
	language: eng,
	issn: 1478-1913,
	superior_ppn: 341340766,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: David D.,
			last_name: Grafton,
			type: author,
		},
	],
	keywords: [ Book Review, Book Review ],
}
erased field '650a' due to removal filter '^Book Reviews?'
Generated record with hash 'FABD2EA9C3ED082AA69FD0DDE27A5923032BA426'

Conversion complete

**Comment by IxKo** [comment]
Wenn ich das Regex 
remove_marc_field_650a     = "^Book Reviews?"
zotero_review_regex        = "^Book Reviews?"
aus der Conf einfüge, klappt es, ja.

**Comment by socheres** [comment]
ja, habe in der conf ergänzt(siehe timeline oben).https://github.com/ubtue/zotero-enhancement-maps/commit/a1e7f7de37e673dde4395a9ffbcd80bd5ad6defd
In solchen eindeutigen Fällen schließe ich das Issue gleich, damit Sie am nächsten Tag nicht nochmal testen müssen. harverst.conf wird täglich um 19.00 aktualisiert.
