### ISSUE TITLE
ISSN 1467-8519 | Bioethics | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1047]
Rezensionen werden nicht erkannt:
https://onlinelibrary.wiley.com/toc/14678519/2020/34/5
https://onlinelibrary.wiley.com/doi/10.1111/bioe.12729

![grafik](https://user-images.githubusercontent.com/29707105/87441916-f36db700-c5f3-11ea-8cc9-ac19b7a977de.png)

**Comment by socheres** [comment]
mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_9A033q" "--output-filename=kzJr6y.xml"  "--config-overrides=remove_marc_field_650a    = "^Book Reviews?" zotero_review_regex       = "^Book Reviews?""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://onlinelibrary.wiley.com/doi/10.1111/bioe.12729"  "Bioethics"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Bioethics' \| DIRECT @ https://onlinelibrary.wiley.com/doi/10.1111/bioe.12729 set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [Bioethics...] \| https://onlinelibrary.wiley.com/doi/10.1111/bioe.12729 {13975854628882156121} Harvest successful     Converting item 1 [Bioethics...] \| https://onlinelibrary.wiley.com/doi/10.1111/bioe.12729 {13975854628882156121} use online ISSN "1467-8519" with online PPN "271596708" post-processed author first name = 'Walter', last name = 'Glannon', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/bioe.12729, 	item_type: review, 	title: Altered Inheritance: CRISPR and the Ethics of Human Genome Editing Françoise Baylis Cambridge, MA, USA: Harvard University Press: 2019. 287 pp. ISBN 9780674976719. US$24.95 (Hardcover), 	short_title: Altered Inheritance, 	publication_title: Bioethics, 	volume: 34, 	issue: 5, 	pages: 555-556, 	date: 2020-01-01, 	doi: 10.1111/bioe.12729, 	language: eng, 	issn: 1467-8519, 	superior_ppn: 271596708, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Walter, 			last_name: Glannon, 			type: author, 		}, 	], 	keywords: [ Book Review, Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash '3362DC35388CAEF8BFDBA585C029270B7081C758'  Conversion complete   Generated 1 record(s) for item 1 [Bioethics...] \| https://onlinelibrary.wiley.com/doi/10.1111/bioe.12729 {13975854628882156121}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
