### ISSUE TITLE
ISSN 1018-1539 | Österreichisches Religionspädagogisches Forum (OJS) | Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1804]
#### URL
https://oerf-journal.eu/index.php/oerf/article/view/316
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Es befindet sich ein weiteres englischsprachiges Abstract im Quellcode, was weder im halb- noch vollautomatische Verfahren mitgeliefert wird:

`<meta name="DC.Description" xml:lang="en" content="This article outlines the research project EthOS. The project deals with the implementation of the subject ethics in Austrian high schools. It focuses on students' expectations regarding the subject, experiences of teachers during the introduction as well as the achievement of ethical competence. One part of the article presents the theoretical framework of the competence model on which ethics lessons are based. It ends with a first insight into the survey of students regarding their expectations of ethics lessons."/>`

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das zweite Abstract sollte jetzt im zotkat auch mitkommen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das zweite Abstract sollte jetzt auch im vollautomatischen Verfahren mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Im halbautomatischen Verfahren wird das zweite Abstract importiert.

**Comment by jriedl** [comment]
Zeitschrift ist live, Rückportierung bisher nur auf nu.

**Comment by jriedl** [comment]
Aktueller Stand jetzt auch auf ub28. Das zweite Abstract wird mitgeliefert, allerdings sofort wieder verworfen, da es auf den allgemeinen Ausschlussfilter matched:  `erased field '520a' due to removal filter '(?i)(published\son\s\d{2}\s\D{3}\s\d{4}\sby\s|not\s+available|Book\sreviews|Books\sreceived|Introduction|Book\snotices|Chronicles|Louvain\schronicle|Table\sof\scontents|\W\s\W\s\W\s\W|No\sabstract\sis\savailable|Rezension\s(zu)?|Inhaltsverzeichnis|Editorial|xxx)'`
Wenn man obigen Regex anchored (`^(?i)(published\son\s\d{2}\s\D{3}\s\d{4}\sby\s|not\s+available|Book\sreviews|Books\sreceived|Introduction|Book\snotices|Chronicles|Louvain\schronicle|Table\sof\scontents|\W\s\W\s\W\s\W|No\sabstract\sis\savailable|Rezension\s(zu)?|Inhaltsverzeichnis|Editorial|xxx)$`) wird es integriert, eventuell war es allerdings ursprünglich eine bewusste Entscheidung, das nicht zu tun.

**Comment by IxKo** [comment]
Oje, das war nicht beabsichtigt, und danke für den Hinweis. Ich kenne mich mit RegEx wenig aus.
ich habe es aber nun hoffentlich so angepasst, dass es eine Anfangsbedingung und teils eine Endbedingung geben soll.
