### ISSUE TITLE
ISSN 1758-6623 | The ecumenical review | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#709]
Rezensionen werden nicht als solche getagt. 
Vgl. Hash C1F6E2DE89D7135EEA5209E9ADAFCD9D86121BCC
https://onlinelibrary.wiley.com/doi/10.1111/erev.12496

**Comment by socheres** [comment]
mit @shadeMe

**Comment by IxKo** [comment]
Rezensionen werden weiterhin nicht richtig in 655 ausgegeben.
Stattdessen erhalten sie folgendes Keyword:
<datafield tag="650" ind1=" " ind2="4"><subfield code="a">Book Review, Book Review</subfield></datafield>

**Comment by socheres** [comment]
mit "Try URL" getestet. `remove_marc_field_650a    = "^Book Reviews?"
zotero_review_regex       = "^Book Reviews?"`

**Comment by socheres** [comment]
gelöst.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_qWTas4" "--output-filename=Xz80pS.xml"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://onlinelibrary.wiley.com/doi/10.1111/erev.12496" "The  ecumenical review"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'The ecumenical review' \| DIRECT @ https://onlinelibrary.wiley.com/doi/10.1111/erev.12496 set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [The ecumenical revie...] \| https://onlinelibrary.wiley.com/doi/10.1111/erev.12496 {18205518303650867413} Harvest successful     Converting item 1 [The ecumenical revie...] \| https://onlinelibrary.wiley.com/doi/10.1111/erev.12496 {18205518303650867413} use online ISSN "1758-6623" with online PPN "340878193" post-processed author first name = 'Iuliu-Marius', last name = 'Morariu', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/erev.12496, 	item_type: review, 	title: Elisabeth Behr-Sigel, En marche vers l’unité. Point de vue d’une théologienne orthodoxe (On the road to unity. The point of view of an Orthodox theologian), ed. with a preface by Olga Lossky. Paris: Les Éditions du Cerf, 2017. 340 pp., 	short_title: Elisabeth Behr-Sigel, En marche vers l’unité. Point de vue d’une théologienne orthodoxe (On the road to unity. The point of view of an Orthodox theologian), ed. with a preface by Olga Lossky. Paris, 	publication_title: The Ecumenical Review, 	volume: 72, 	issue: 1, 	pages: 151-152, 	date: 2020-01-01, 	doi: 10.1111/erev.12496, 	language: eng, 	issn: 1758-6623, 	superior_ppn: 340878193, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Iuliu-Marius, 			last_name: Morariu, 			type: author, 		}, 	], 	keywords: [ Book Review, Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash '9B2C7FFCA04F80AD08CFE65B66BA0FF15E9DEE55'  Conversion complete   Generated 1 record(s) for item 1 [The ecumenical revie...] \| https://onlinelibrary.wiley.com/doi/10.1111/erev.12496 {18205518303650867413}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
