### ISSUE TITLE
ISSN 2161-4504 | Journal of pastoral theology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#833]
Rezensionen werden nicht erkannt. Dies ist sowohl beim voll- als auch beim halbautomatischen Verfahren der Fall.
Vgl vollautomatisch IxTheo#2020-02-28#6772AD8AE7765DC4A82EF7038CBD076A6702FEA6
https://www.tandfonline.com/toc/ypat20/29/3?nav=tocList
https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1673042
bereits in #787 erwähnt
halbautomatisch etwa bei:
https://www.tandfonline.com/doi/full/10.1080/10649867.2020.1712872

**Comment by socheres** [comment]
Mit "Try URL getestet."

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_q6IH7B" "--output-filename=1r4wUa.xml"  "--config-overrides=remove_marc_field_650a    = "^Book Reviews?$" zotero_review_regex       = "^Book Reviews""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL"  "https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1673042"  "Journal of pastoral theology"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of pastoral theology' \| DIRECT @ https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1673042 set download-delay for domain 'www.tandfonline.com' to 1000 ms   Harvesting URL 1 [Journal of pastoral ...] \| https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1673042 {2791414156912448373} Harvest successful     Converting item 1 [Journal of pastoral ...] \| https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1673042 {2791414156912448373} use online ISSN "2161-4504" with online PPN "845731157" post-processed author first name = 'Phillis Isabella', last name = 'Sheppard', title = '', affix = '' added GND number 143942999 for author Sheppard, Phillis Isabella (SWB lookup) language set to default language 'eng' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1080/10649867.2019.1673042, 	item_type: review, 	title: Object Relations, Buddhism, and Relationality in Womanist Practical Theology, 	publication_title: Journal of Pastoral Theology, 	volume: 29, 	issue: 3, 	pages: 188-189, 	date: 2019-09-02, 	doi: 10.1080/10649867.2019.1673042, 	language: eng, 	issn: 2161-4504, 	superior_ppn: 845731157, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Phillis Isabella, 			last_name: Sheppard, 			type: author, 			gnd_number: 143942999, 		}, 	], 	keywords: [ Book Reviews ], } erased field '650a' due to removal filter '^Book Reviews?$' Generated record with hash '369DF9076E52173522AD2D57D1FF80D86D0829B1'  Conversion complete   Generated 1 record(s) for item 1 [Journal of pastoral ...] \| https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1673042 {2791414156912448373}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
