### ISSUE TITLE
ISSN 1862-5886 | Zeitschrift für junge Religionswissenschaft | Call for Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#847]
Diese Artikel sollten nicht erfasst werden:
IxTheo#2020-04-06#80B49010A317B026130A388B228E441E3FD89491

Call for Reviews ist ein Punkt, der sich im Menu auf der linken Seite befindet und hat nichts mit dem Inhalt des Hefts zu tun:
![grafik](https://user-images.githubusercontent.com/29707105/78558845-9784dc80-7813-11ea-9c82-b8a558c44fbb.png)

**Comment by socheres** [comment]
Wird nicht mehr erfasst.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_7YIqSV" "--output-filename=bu7lRG.xml"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.openedition.org/zjr/1140" "Zeitschrift für  junge Religionswissenschaft"
-- | --
Runtime | 15s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Zeitschrift für junge Religionswissenschaft' \| DIRECT @ https://journals.openedition.org/zjr/1140 set download-delay for domain 'journals.openedition.org' to 1000 ms   Harvesting URL 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} multiple articles found => trying to harvest children caching download for URL http://journals.openedition.org/zjr/1156 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} caching download for URL http://journals.openedition.org/zjr/1147 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} caching download for URL http://journals.openedition.org/zjr/1164 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} caching download for URL http://journals.openedition.org/zjr/1173 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} caching download for URL http://journals.openedition.org/zjr/1203 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} caching download for URL http://journals.openedition.org/zjr/1184 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} caching download for URL http://journals.openedition.org/zjr/1224 @ item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} cached 7 items from a multi-result response Harvest successful     Converting item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981} use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Anja', last name = 'Kirsch', title = '', affix = '' added GND number 1089832281 for author Kirsch, Anja (SWB lookup) post-processed author first name = 'Andrea', last name = 'Rota', title = '', affix = '' added GND number 106743917X for author Rota, Andrea (SWB lookup) post-processed author first name = 'Jens', last name = 'Schlieter', title = '', affix = '' added GND number 115853294 for author Schlieter, Jens (SWB lookup) Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1156, 	item_type: journalArticle, 	title: Multiple Religious Identities: Students’ Interviews with Keynote Speakers of the 2018 EASR Conference, Bern. Introductory Remarks: Turning an Academic Conference into a Master’s Seminar, 	short_title: Multiple Religious Identities, 	abstract_note: The conference From June 17 to 21, 2018, the Institute for the Science of Religion at the University of Bern, Switzerland, together with the Swiss Society for the Study of Religions organized and hosted the Sixteenth Annual Conference of the European Association for the Study of Religions (EASR). The conference was entitled »Multiple Religious Identities – Individuals, Communities, Traditions« and provided more than five hundred scholars of religion from forty-three countries with a forum to ..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: eng, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Anja, 			last_name: Kirsch, 			type: author, 			gnd_number: 1089832281, 		}, 		{ 			first_name: Andrea, 			last_name: Rota, 			type: author, 			gnd_number: 106743917X, 		}, 		{ 			first_name: Jens, 			last_name: Schlieter, 			type: author, 			gnd_number: 115853294, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash '6E57B51BE409914B40802AB4D4C93941A3203DBB'  use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Valeriya', last name = 'Chernova', title = '', affix = '' post-processed author first name = 'Jana', last name = 'Lehmann', title = '', affix = '' post-processed author first name = 'Kathleen', last name = 'Hellermann', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1147, 	item_type: journalArticle, 	title: Interview with Milda Ališauskienė. Keynote Speaker of the 2018 EASR Conference, Bern, 	abstract_note: Professor Ališauskienė, thank you for joining us. You belong to a younger generation of scholars working on religion in post-Soviet countries with a focus on new religious movements. Where does your interest in new religious movements come from? During my bachelor’s studies at Vilnius Pedagogical University, I was captivated by courses on new religious movements and the sociology of religion. The theoretical paradigm in the latter was the secularization thesis, and I focused on the seculariza..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: eng, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Valeriya, 			last_name: Chernova, 			type: author, 		}, 		{ 			first_name: Jana, 			last_name: Lehmann, 			type: author, 		}, 		{ 			first_name: Kathleen, 			last_name: Hellermann, 			type: author, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash 'F87AACA206A4ADB171886E450F002D7D16AD21E2'  use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Sophie', last name = 'Meyer', title = '', affix = '' post-processed author first name = 'Janina', last name = 'Sorger-Rachidi', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1164, 	item_type: journalArticle, 	title: Interview with Grace Davie. Keynote Speaker of the 2018 EASR Conference, Bern, 	abstract_note: Professor Davie, thank you for accepting this interview. In your keynote speech, you talked about your work with colleagues from different fields of study and from various cultural and religious backgrounds. Why is this kind of collaboration so important? I can remember the moment when I decided that I wanted to work comparatively. I am not anywhere near as good with languages as you are, but I could already speak French as a junior scholar, which was unusual among British social scientists. ..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: eng, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Sophie, 			last_name: Meyer, 			type: author, 		}, 		{ 			first_name: Janina, 			last_name: Sorger-Rachidi, 			type: author, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash 'FA6B72E1F7682C6E071121D6CFAFEC2C2C81AB31'  use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Michaela', last name = 'Wisler', title = '', affix = '' post-processed author first name = 'Rebecca', last name = 'Farner', title = '', affix = '' post-processed author first name = 'Ilona', last name = 'Ryser', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1173, 	item_type: journalArticle, 	title: Interview with Jörg Rüpke. Keynote Speaker of the 2018 EASR Conference, Bern, 	abstract_note: Professor Rüpke, thank you very much for agreeing to this interview. In your keynote lecture, you addressed religious changes due to processes of urbanization in Roman antiquity. We would like to start with a more general question: How could the concept of multiple religious identities be relevant to your field of research? I like this concept in contrast to concepts like religious pluralism, which is often used in the sense of a plurality of neatly separated religions being present in the sa..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: eng, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Michaela, 			last_name: Wisler, 			type: author, 		}, 		{ 			first_name: Rebecca, 			last_name: Farner, 			type: author, 		}, 		{ 			first_name: Ilona, 			last_name: Ryser, 			type: author, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash '1B71E2E3D54A3CD131CA39F348E5E06E25DA73D9'  use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Ilona', last name = 'Ryser', title = '', affix = '' post-processed author first name = 'Janina', last name = 'Sorger-Rachidi', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1203, 	item_type: journalArticle, 	title: Interview with Reinhard Schulze. Keynote Speaker of the 2018 EASR Conference, Bern, 	abstract_note: Professor Schulze, since this event has brought together researchers from all over Europe with a great variety of opinions, perspectives, methods, and theories regarding multiple religious identities, we would like to begin this interview by asking how you understand the concept of multiple religious identities and where you see the most important aspects of this concept, especially in your own research. As I tried to show in my presentation, the advantage of multiple religious identities lie..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: eng, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Ilona, 			last_name: Ryser, 			type: author, 		}, 		{ 			first_name: Janina, 			last_name: Sorger-Rachidi, 			type: author, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash '95040C54A35EA41AA953A26560BD722BA1F45C1B'  use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Sara', last name = 'Wenzinger', title = '', affix = '' post-processed author first name = 'Luzia', last name = 'Kunz', title = '', affix = '' post-processed author first name = 'Jenny', last name = 'Nerlich', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1184, 	item_type: journalArticle, 	title: Interview with Dorothea Weltecke. Keynote Speaker of the 2018 EASR Conference, Bern, 	abstract_note: Professor Weltecke, thank you very much for being with us. In your talk, you presented examples of religious pluralism in the Middle Ages and suggested three models to conceptualize medieval religion. What are, from your point of view, the most important factors that restricted and limited religious choice in the Middle Ages? I think that the driving force limiting choices was the reality of social inequality. The distinction between the faithful, the unfaithful, and the tolerated was, for ex..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: eng, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Sara, 			last_name: Wenzinger, 			type: author, 		}, 		{ 			first_name: Luzia, 			last_name: Kunz, 			type: author, 		}, 		{ 			first_name: Jenny, 			last_name: Nerlich, 			type: author, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash '4794910032E29777E1F10F6CA740CBACAA458E59'  use online ISSN "1862-5886" with online PPN "514530790" post-processed author first name = 'Nicole', last name = 'Ulm', title = '', affix = '' post-processed author first name = 'Fabian', last name = 'Vogel', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/zjr/1224, 	item_type: journalArticle, 	title: Religion in Relation. Bericht zur 33. Jahrestagung der Deutschen Vereinigung für Religionswissenschaft (DVRW) zum Thema "Konzeptualisierungen von Religion", ausgerichtet an der Leibniz Universität Hannover vom 3. – 6. September 2019, 	abstract_note: Das kürzlich selbstständig gewordene Institut für Religionswissenschaft der Leibniz Universität Hannover richtete in diesem Jahr die Tagung der DVRW aus. An drei Tagen trafen sich nicht nur Vertreter*innen der deutschsprachigen Religionswissenschaft, sondern auch für eine Tagung der DVRW ungewöhnlich viele internationale Fachvertreter*innen. Die dadurch mit dem Titel einer IAHR Special Conference versehene Tagung stand unter dem Thema „Konzeptualisierungen von Religion.“ Somit sollten unter d..., 	publication_title: Zeitschrift für junge Religionswissenschaft, 	issue: 14, 	date: 2019-05-19, 	language: ger, 	issn: 1862-5886, 	superior_ppn: 514530790, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Nicole, 			last_name: Ulm, 			type: author, 		}, 		{ 			first_name: Fabian, 			last_name: Vogel, 			type: author, 		}, 	], } erased field '520a' due to removal filter '.*' Generated record with hash 'CE1CBF05FF9D404D04148A7B9999EF28E0FBEB98'  Conversion complete   Generated 7 record(s) for item 1 [Zeitschrift für jung...] \| https://journals.openedition.org/zjr/1140 {16561262587316415981}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 7 		Successful: 7 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 7
