### ISSUE TITLE
ISSN 2050-3040 | Critical Research on Religion | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#852]
Rezensionen werden nicht getagt. Etwa hier:
https://journals.sagepub.com/toc/crra/8/1
Abgesehen davon, dass sie in der Sektion Book Reviews stehen findet sich auf der Einzelseite immer der Text Reviewed by ...
siehe z.  B. https://journals.sagepub.com/doi/full/10.1177/2050303219900248

**Comment by socheres** [comment]
zotat

**Comment by socheres** [comment]
mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_zV1ZEz" "--output-filename=Slgb0K.xml"  "--config-overrides=remove_marc_field_650a = "^Book Reviews?$" zotero_review_regex    = "^Book Reviews?$""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.sagepub.com/doi/full/10.1177/2050303219900248"  "Critical Research on Religion"
-- | --
Runtime | 7s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Critical Research on Religion' \| DIRECT @ https://journals.sagepub.com/doi/full/10.1177/2050303219900248 set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [Critical Research on...] \| https://journals.sagepub.com/doi/full/10.1177/2050303219900248 {10164260292434951115} Harvest successful     Converting item 1 [Critical Research on...] \| https://journals.sagepub.com/doi/full/10.1177/2050303219900248 {10164260292434951115} use online ISSN "2050-3040" with online PPN "757132022" post-processed author first name = 'George', last name = 'González', title = '', affix = '' expected language 'eng' but found 'en' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/2050303219900248, 	item_type: review, 	title: Francis Stewart, Punk Rock Is My Religion—Straight Edge Punk and ‘Religious’ Identity, 	publication_title: Critical Research on Religion, 	volume: 8, 	issue: 1, 	pages: 101-104, 	date: 2020-04-01, 	doi: 10.1177/2050303219900248, 	language: eng, 	issn: 2050-3040, 	superior_ppn: 757132022, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: George, 			last_name: González, 			type: author, 		}, 	], 	keywords: [ Book Review ], } erased field '650a' due to removal filter '^Book Reviews?$' Generated record with hash '97708529B6CCD7EAAA5A7E38FCD0B6DBFB443323'  Conversion complete   Generated 1 record(s) for item 1 [Critical Research on...] \| https://journals.sagepub.com/doi/full/10.1177/2050303219900248 {10164260292434951115}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
