### ISSUE TITLE
ISSN 1468-0025 | Modern Theology | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#892]
Auch bei einem Review Essay handelt es sich um eine Rezension. Dies wird hier nicht erfasst:
IxTheo#2020-03-05#71CEDCD558F28A07131B5B62153543B860825C43
https://onlinelibrary.wiley.com/doi/10.1111/moth.12556

**Comment by socheres** [comment]
mit "Try URL" getestet. 


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_wuxySP" "--output-filename=bIimOD.xml"  "--config-overrides=remove_marc_field_650a     = "^(Book  Reviews?)$\|^(Review Essays?)" zotero_review_regex        = "^(Book Reviews?)$\|^(Review Essays?)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://onlinelibrary.wiley.com/doi/10.1111/moth.12556" "Modern  theology"
-- | --
Runtime | 7s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Modern theology' \| DIRECT @ https://onlinelibrary.wiley.com/doi/10.1111/moth.12556 set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [Modern theology...] \| https://onlinelibrary.wiley.com/doi/10.1111/moth.12556 {15003847553046091873} Harvest successful     Converting item 1 [Modern theology...] \| https://onlinelibrary.wiley.com/doi/10.1111/moth.12556 {15003847553046091873} use online ISSN "1468-0025" with online PPN "320573281" post-processed author first name = 'Joseph', last name = 'Rivera', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/moth.12556, 	item_type: review, 	title: Political Liberalism and Resentment: A Theological Rejoinder, 	short_title: Political Liberalism and Resentment, 	publication_title: Modern Theology, 	volume: 36, 	issue: 2, 	pages: 420-427, 	date: 2020-01-01, 	doi: 10.1111/moth.12556, 	language: eng, 	issn: 1468-0025, 	superior_ppn: 320573281, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Joseph, 			last_name: Rivera, 			type: author, 		}, 	], 	keywords: [ Review Essay, Review Essay ], } erased field '650a' due to removal filter '^(Book Reviews?)$\|^(Review Essays?)' Generated record with hash '1919966C14B69229AA66EC4FEDA103D7D4E9016A'  Conversion complete   Generated 1 record(s) for item 1 [Modern theology...] \| https://onlinelibrary.wiley.com/doi/10.1111/moth.12556 {15003847553046091873}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
