### ISSUE TITLE
ISSN 1552-146X | The Hastings Center report | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#910]
Rezensionen werden nicht getagt. Das ist eine:
https://onlinelibrary.wiley.com/doi/10.1002/hast.1101
https://onlinelibrary.wiley.com/toc/1552146x/2020/50/2
IxTheo#2020-04-23#012174AA6CA61AE06178F712131B63797ADC9E41

**Comment by socheres** [comment]
mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_JxgK7g" "--output-filename=6dAu47.xml"  "--config-overrides=remove_marc_field_650a     = "^review$" zotero_review_regex        = "^review""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://onlinelibrary.wiley.com/doi/10.1002/hast.1101" "The  Hastings Center report"
-- | --
Runtime | 8s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'The Hastings Center report' \| DIRECT @ https://onlinelibrary.wiley.com/doi/10.1002/hast.1101 set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [The Hastings Center ...] \| https://onlinelibrary.wiley.com/doi/10.1002/hast.1101 {2561213706154360895} Harvest successful     Converting item 1 [The Hastings Center ...] \| https://onlinelibrary.wiley.com/doi/10.1002/hast.1101 {2561213706154360895} use online ISSN "1552-146X" with online PPN "341346551" post-processed author first name = 'James', last name = 'Dwyer', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1002/hast.1101, 	item_type: review, 	title: Green Bioethics and Hope, 	abstract_note: Many environmental problems are now more serious and urgent than ever. In high-income countries, health care is part of the problem. In Principles of Green Bioethics: Sustainability in Health Care, Cristina Richie focuses on medical developments, techniques, and procedures, and she proposes four principles for green bioethics: distributive justice, resource conservation, simplicity, and ethical economics. Richie is right to emphasize the need for green bioethics, and I admire her aim to bring environmental concerns back into bioethics, but I was disappointed with this book. Since Plato, much of ethics has focused on the characteristics or principles of the ideally just society. This work in ethics seeks to transcend the culture in which we live in order to provide guidance about what we should do. I think it would be better to start with the messy, problematic, and unjust situations in which we are enmeshed., 	publication_title: Hastings Center Report, 	volume: 50, 	issue: 2, 	pages: 44-45, 	date: 2020-01-01, 	doi: 10.1002/hast.1101, 	language: eng, 	issn: 1552-146X, 	superior_ppn: 341346551, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: James, 			last_name: Dwyer, 			type: author, 		}, 	], 	keywords: [ green bioethics, environmental ethics, health care, justice, review, review ], } Generated record with hash '44CD882B7DA269B753517656FBCD21C5AEA9CC27'  Conversion complete   Generated 1 record(s) for item 1 [The Hastings Center ...] \| https://onlinelibrary.wiley.com/doi/10.1002/hast.1101 {2561213706154360895}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
