### ISSUE TITLE
ISSN 1468-2265 | Heythrop journal | Escape Character & ?

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#925]
Hier wird nur Shakespeare als Titel ausgegeben. In Wirklichkeit lautet er "Shakespeare & London. By Salkeld, Duncan. Pp. 187, Oxford University Press, $65.00"
Ist das & ein Zeichen, das zum Abbruch führt? Es scheint mir ein globales Problem zu sein.
IxTheo#2020-04-29#4341E89C7B83B6EDF118B3CF75E9A7056DE056E9
https://onlinelibrary.wiley.com/doi/10.1111/heyj.13526

**Comment by socheres** [comment]
Mit Client wird der Titel nicht nach "&" abgeschnitten. @mtrojan-ub liegt es an dem Harvester?

**Comment by socheres** [comment]
mit "Try URL" getestet. Review-Muster angepasst.

Command | /usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/ZtsMaps_y7ILvQ" "--output-filename=TNA3eJ.xml" "--config-overrides=remove_marc_field_650a = "^Book Reviews?" zotero_review_regex = "^Book Reviews?" exclude_if_marc_field_245a = "(^Editorial Board$)\|(^Issue Information)"" "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "URL" "https://onlinelibrary.wiley.com/doi/10.1111/heyj.13526" "Heythrop journal : a bimonthly review of philosophy and theology"
-- | --
Runtime | 4s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Heythrop journal : a bimonthly review of philosophy and theology' \| DIRECT @ https://onlinelibrary.wiley.com/doi/10.1111/heyj.13526 set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [Heythrop journal : a...] \| https://onlinelibrary.wiley.com/doi/10.1111/heyj.13526 {15226773626210813310} Harvest successful     Converting item 1 [Heythrop journal : a...] \| https://onlinelibrary.wiley.com/doi/10.1111/heyj.13526 {15226773626210813310} use online ISSN "1468-2265" with online PPN "320573052" post-processed author first name = 'Andrea', last name = 'Campana', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/heyj.13526, 	item_type: review, 	title: Shakespeare & London. By Duncan Salkeld. Pp. 187, Oxford University Press, $65.00., 	publication_title: The Heythrop Journal, 	volume: 61, 	issue: 3, 	pages: 538-541, 	date: 2020-01-01, 	doi: 10.1111/heyj.13526, 	language: eng, 	issn: 1468-2265, 	superior_ppn: 320573052, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Andrea, 			last_name: Campana, 			type: author, 		}, 	], 	keywords: [ Book Review, Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash 'BA4798841F3A581C4C9D8FF1C4E8B126E747932D'  Conversion complete   Generated 1 record(s) for item 1 [Heythrop journal : a...] \| https://onlinelibrary.wiley.com/doi/10.1111/heyj.13526 {15226773626210813310}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
