### ISSUE TITLE
ISSN 0739-8913 | Christian education journal | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#935]
Rezensionen werden nicht getagt:
IxTheo#2020-04-30#DA83BFEB237867D970F6B4981C855F3562AFB23C
https://journals.sagepub.com/doi/full/10.1177/0739891319882947i
Fehlender Eintrag in der ini:
https://github.com/ubtue/zotero-enhancement-maps/blob/e739a00ba07389390f10dc95a6af40737f6d1e56/zotero_harvester.conf#L3178

**Comment by socheres** [comment]
Mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_ShRKTi" "--output-filename=GLMP8e.xml"  "--config-overrides=remove_marc_field_650a     = "^Book Reviews?" zotero_review_regex        = "^Book Reviews?""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.sagepub.com/doi/full/10.1177/0739891319882947i"  "Trends in organized crime"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Trends in organized crime' \| DIRECT @ https://journals.sagepub.com/doi/full/10.1177/0739891319882947i set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [Trends in organized ...] \| https://journals.sagepub.com/doi/full/10.1177/0739891319882947i {12079255872270307527} Harvest successful     Converting item 1 [Trends in organized ...] \| https://journals.sagepub.com/doi/full/10.1177/0739891319882947i {12079255872270307527} use online ISSN "1936-4830" with online PPN "32051806X" post-processed author first name = 'Ok Soon', last name = 'Kim', title = '', affix = '' added GND number 115829560X for author Kim, Ok Soon (SWB lookup) keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/0739891319882947i, 	item_type: review, 	title: Book review: A Guide to Christian Spiritual Formation: How Scripture, Spirit, Community, and Mission Shape Our Souls, by Evan B. Howard, 	short_title: Book review, 	publication_title: Christian Education Journal, 	volume: 17, 	issue: 1, 	pages: 199-202, 	date: 2020-04-01, 	doi: 10.1177/0739891319882947i, 	language: eng, 	issn: 1936-4830, 	superior_ppn: 32051806X, 	superior_type: 2, 	ssg: 4, 	creators: [ 		{ 			first_name: Ok Soon, 			last_name: Kim, 			type: author, 			gnd_number: 115829560X, 		}, 	], 	keywords: [ Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash 'E2CF35C342EB225916D3E4A6D6F91AEBB0C29519'  Conversion complete   Generated 1 record(s) for item 1 [Trends in organized ...] \| https://journals.sagepub.com/doi/full/10.1177/0739891319882947i {12079255872270307527}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		KrimDok: 1
