### ISSUE TITLE
ISSN 2397-3498 | Downside Review | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#939]
Rezensionen werden nicht getagt, bekommen statt dessen ein Schlagwort.
 IxTheo#2020-05-05#249A0DBB6E40667D8507A0FBAA872B1C522D0793
https://journals.sagepub.com/doi/full/10.1177/0012580620910515
Fehlender Eintrag in der ini:
https://github.com/ubtue/zotero-enhancement-maps/blob/fc728e3f73f13299f4601d5eb366c6212b463586/zotero_harvester.conf#L3222

**Comment by socheres** [comment]
mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_2Ygjd5" "--output-filename=kckeT1.xml"  "--config-overrides=remove_marc_field_650a    = "^Book Reviews?" zotero_review_regex       = "^Book Reviews?""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.sagepub.com/doi/full/10.1177/0012580620910515"  "Downside review : a quarterly of catholic thought and of monastic  history"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Downside review : a quarterly of catholic thought and of monastic history' \| DIRECT @ https://journals.sagepub.com/doi/full/10.1177/0012580620910515 set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [Downside review : a ...] \| https://journals.sagepub.com/doi/full/10.1177/0012580620910515 {1154540560299566020} Harvest successful     Converting item 1 [Downside review : a ...] \| https://journals.sagepub.com/doi/full/10.1177/0012580620910515 {1154540560299566020} use online ISSN "2397-3498" with online PPN "853803978" post-processed author first name = 'Dom Anselm', last name = 'Brumwell', title = '', affix = '' title matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/0012580620910515, 	item_type: review, 	title: Book Review: Daniel Joslyn-Siemiatowski, The More Torah, The More Life: A Christian Commentary on Mishnah Avot (Christian Commentaries on Non-Christian Sacred Texts), 	short_title: Book Review, 	publication_title: The Downside Review, 	volume: 138, 	issue: 1, 	pages: 38-39, 	date: 2020-01-01, 	doi: 10.1177/0012580620910515, 	language: eng, 	issn: 2397-3498, 	superior_ppn: 853803978, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Dom Anselm, 			last_name: Brumwell, 			type: author, 		}, 	], 	keywords: [ Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash '7759927A6338953A7DA0B082851D3A330B1A2EB8'  Conversion complete   Generated 1 record(s) for item 1 [Downside review : a ...] \| https://journals.sagepub.com/doi/full/10.1177/0012580620910515 {1154540560299566020}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
