### ISSUE TITLE
ISSN 1759-8931 | Transformation | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#941]
Rezensionen werden nicht getagt, bekommen statt dessen ein Schlagwort.
IxTheo#2020-05-05#9BF5934F275BE2FF5349FB1A68EA4CE9A38E4FDB
https://journals.sagepub.com/doi/full/10.1177/0265378820907645
Fehlender Eintrag in der ini
https://github.com/ubtue/zotero-enhancement-maps/blob/fc728e3f73f13299f4601d5eb366c6212b463586/zotero_harvester.conf#L3429

**Comment by socheres** [comment]
Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_gnNG0W" "--output-filename=ni7HNh.xml"  "--config-overrides=remove_marc_field_650a = "^Book Reviews?" zotero_review_regex    = "^Book Reviews?""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.sagepub.com/doi/full/10.1177/0265378820907645"  "Transformation : an international journal of holistic mission studies"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Transformation : an international journal of holistic mission studies' \| DIRECT @ https://journals.sagepub.com/doi/full/10.1177/0265378820907645 set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [Transformation : an ...] \| https://journals.sagepub.com/doi/full/10.1177/0265378820907645 {16923283699175629515} Harvest successful     Converting item 1 [Transformation : an ...] \| https://journals.sagepub.com/doi/full/10.1177/0265378820907645 {16923283699175629515} use online ISSN "1759-8931" with online PPN "35786574X" post-processed author first name = 'Dejan', last name = 'Azdajic', title = '', affix = '' added GND number 1204523533 for author Azdajic, Dejan (SWB lookup) keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/0265378820907645, 	item_type: review, 	title: Book review: Mission and Evangelism in a Secularizing World: Academy, Agency, and Assembly Perspectives From Canada, 	short_title: Book review, 	publication_title: Transformation, 	volume: 37, 	issue: 2, 	pages: 165-166, 	date: 2020-04-01, 	doi: 10.1177/0265378820907645, 	language: eng, 	issn: 1759-8931, 	superior_ppn: 35786574X, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Dejan, 			last_name: Azdajic, 			type: author, 			gnd_number: 1204523533, 		}, 	], 	keywords: [ Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash 'D3871A2B61F70E09D986CAC54BF4BAF9F086D54B'  Conversion complete   Generated 1 record(s) for item 1 [Transformation : an ...] \| https://journals.sagepub.com/doi/full/10.1177/0265378820907645 {16923283699175629515}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
