### ISSUE TITLE
ISSN 2044-2696 | Theology | Rezensionen 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#947]
Rezensionen werden nicht getagt, bekommen statt dessen ein Schlagwort. 
Vgl. IxTheo#2020-05-09#8C341E4D2297A2AFE752608A3C9C8FC9FE0C1C3E
Ini ergänzen? Vgl.
https://github.com/ubtue/zotero-enhancement-maps/blob/39bde9a3be825c539770dec74a70d81bbc9e8503/zotero_harvester.conf#L3393

**Comment by socheres** [comment]
Mit "Try URL getestet"
Titel "Editorial" wird auch ausgeschlossen.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_IWxfNG" "--output-filename=UqV51M.xml"  "--config-overrides=remove_marc_field_650a    = "^Book Reviews?" zotero_review_regex       = "^Book Reviews?" exclude_if_marc_field_245a = "^Editorial""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.sagepub.com/doi/full/10.1177/0040571X19894860m"  "Theology : a monthly journal of historic christianity"
-- | --
Runtime | 4s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Theology : a monthly journal of historic christianity' \| DIRECT @ https://journals.sagepub.com/doi/full/10.1177/0040571X19894860m set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [Theology : a monthly...] \| https://journals.sagepub.com/doi/full/10.1177/0040571X19894860m {10766524630900596143} Harvest successful     Converting item 1 [Theology : a monthly...] \| https://journals.sagepub.com/doi/full/10.1177/0040571X19894860m {10766524630900596143} use online ISSN "2044-2696" with online PPN "638066778" post-processed author first name = 'Frances', last name = 'Ward', title = '', affix = '' added GND number 1148998799 for author Ward, Frances (SWB lookup) keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/0040571X19894860m, 	item_type: review, 	title: David Jasper, Heaven in Ordinary: Poetry and Religion in a Secular Age, 	short_title: David Jasper, Heaven in Ordinary, 	publication_title: Theology, 	volume: 123, 	issue: 2, 	pages: 149-151, 	date: 2020-03-01, 	doi: 10.1177/0040571X19894860m, 	language: eng, 	issn: 2044-2696, 	superior_ppn: 638066778, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Frances, 			last_name: Ward, 			type: author, 			gnd_number: 1148998799, 		}, 	], 	keywords: [ Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash '33EF0B9975C4495AEFD606F50C3245A80A90CC5B'  Conversion complete   Generated 1 record(s) for item 1 [Theology : a monthly...] \| https://journals.sagepub.com/doi/full/10.1177/0040571X19894860m {10766524630900596143}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
