### ISSUE TITLE
ISSN 2044-2696 | Theology | Rezension Review Article

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#949]
Review Article sind ebenfalls Rezensionen. Sie gehören als solche getagt. Bsp.:
https://journals.sagepub.com/doi/full/10.1177/0040571X20910705
IxTheo#2020-05-09#337D1C394ACA8486E9A7A522B28ABDBE20BFC81A
Ini ergänzen?
https://github.com/ubtue/zotero-enhancement-maps/blob/39bde9a3be825c539770dec74a70d81bbc9e8503/zotero_harvester.conf#L3393

**Comment by socheres** [comment]
kein Muster erkennbar.

**Comment by socheres** [comment]
hier wird zwischen "innerHTML": "Review Article" und "innerHTML": "Researc Article" unterschieden.

**Comment by socheres** [comment]
@mtrojan-ub nach commit bitte "ready for testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by socheres** [comment]
mit "Try URL"getestet.


Command | /usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/ZtsMaps_T2t1tS" "--output-filename=ZlcEAd.xml" "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "URL" "https://journals.sagepub.com/doi/full/10.1177/0040571X20910705" "Theology : a monthly journal of historic christianity"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Theology : a monthly journal of historic christianity' \| DIRECT @ https://journals.sagepub.com/doi/full/10.1177/0040571X20910705 set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [Theology : a monthly...] \| https://journals.sagepub.com/doi/full/10.1177/0040571X20910705 {5007424495163581586} Harvest successful     Converting item 1 [Theology : a monthly...] \| https://journals.sagepub.com/doi/full/10.1177/0040571X20910705 {5007424495163581586} use online ISSN "2044-2696" with online PPN "638066778" post-processed author first name = 'Paul', last name = 'Avis', title = '', affix = '' added GND number 128589086 for author Avis, Paul (SWB lookup) keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/0040571X20910705, 	item_type: review, 	title: Not yet ‘Anglicanism’, 	publication_title: Theology, 	volume: 123, 	issue: 3, 	pages: 198-203, 	date: 2020-05-01, 	doi: 10.1177/0040571X20910705, 	language: eng, 	issn: 2044-2696, 	superior_ppn: 638066778, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Paul, 			last_name: Avis, 			type: author, 			gnd_number: 128589086, 		}, 	], 	keywords: [ Book Review ], } erased field '650a' due to removal filter '^Book Reviews?' Generated record with hash 'A81458277854E3B4EBC33C3F80388E183E96C6AD'  Conversion complete   Generated 1 record(s) for item 1 [Theology : a monthly...] \| https://journals.sagepub.com/doi/full/10.1177/0040571X20910705 {5007424495163581586}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
