### ISSUE TITLE
ISSN 2042-0587 | Studies in religion | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#986]
**URL**
https://journals.sagepub.com/doi/abs/10.1177/0008429820903992?ai=1gvoi&amp;mi=3ricys&amp;af=R
IxTheo#2020-05-22#73E697F3FF5ECDCD1E8A36D1849CB4FA3308C129
**Ausführliche Problembeschreibung**
Rezensionen werden nur als Keyword "Book Review" in 650 getagt.

**Offenbare Lösungen**
Rezensionen in 655 tagen und Keyword in 650 entfernen.

**Comment by socheres** [comment]
mit "Try URL" getestet:

> keywords: [ Book Review ],
}
erased field '650a' due to removal filter '^Book Reviews?'
Generated record with hash '2653DFB6E767ACE57C8EBDEF03BD90ED311FC89C'
Conversion complete
Generated 1 record(s) for item 1 [Studies in religion ...] | https://journals.sagepub.com/doi/full/10.1177/0008429820903992?amp;af=R&ai=1gvoi&mi=3ricys {2710421915422319903}
