### ISSUE TITLE
ISSN 1573-0697 | Journal of business ethics | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#991]
**URL**
https://link.springer.com/article/10.1007/s10551-020-04430-7
keine Einspielungsdatei; Rezension aus älterem Heft mit TRY URL getestet
**Ausführliche Problembeschreibung**
Rezensionen werden nicht erkannt. Sie werden nur mit dem Keyword "Book Reviews" erfasst.

**Offenbare Lösungen**
In 655 als Rezension tagen.

**Comment by socheres** [comment]
Mit "Try URL" getestet.

> keywords: [ Book Reviews ],
}
erased field '650a' due to removal filter '^Book Reviews?$'
Generated record with hash '59CDD978D09FA81959A600EA2CCADF89F3122EFF'
Conversion complete
Generated 1 record(s) for item 1 [Journal of business ...] | https://link.springer.com/article/10.1007/s10551-020-04430-7 {3416355029840667232}

**Comment by IxKo** [comment]
@kdr154 Bei dieser Zs sind momentan keine Issues offen und sie wäre eventuell für den Live-Betrieb möglich. Könntest Du bitte die Zs nochmal testen?
