### ISSUE TITLE
ISSN 2040-4867 | Journal of church and state | 1/17 Rezensionen nicht erkannt

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#994]
**URL**
https://academic.oup.com/jcs/article/62/2/369/5814169?rss=1
IxTheo#2020-05-25#CF8594ED7166D95E544C5D9F831DF44ED2A8261C
**Ausführliche Problembeschreibung**
Alle Rezensionen - bis auf diese - wurden richtig erkannt.

**Offenbare Lösungen**
?

**Comment by socheres** [comment]
Mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_QoydeO" "--output-filename=d3DDpv.xml"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://academic.oup.com/jcs/article/62/2/369/5814169?rss=1"  "Journal of church and state"
-- | --
Runtime | 22s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of church and state' \| DIRECT @ https://academic.oup.com/jcs/article/62/2/369/5814169?rss=1 set download-delay for domain 'academic.oup.com' to 1000 ms   Harvesting URL 1 [Journal of church an...] \| https://academic.oup.com/jcs/article/62/2/369/5814169?rss=1 {12736395429199931726} Harvest successful     Converting item 1 [Journal of church an...] \| https://academic.oup.com/jcs/article/62/2/369/5814169?rss=1 {12736395429199931726} use online ISSN "2040-4867" with online PPN "341338435" post-processed author first name = 'Mark', last name = 'Biondich', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://academic.oup.com/jcs/article/62/2/369/5814169, 	item_type: review, 	title: Disciples of the State?: Religion and State-Building in the Former Ottoman World. By Kristin Fabbe, 	short_title: Disciples of the State?, 	abstract_note: Kristin Fabbe has written a highly engaging study of the historical relationship between religion and state-building in the Middle East and Balkans. Even before, 	publication_title: Journal of Church and State, 	volume: 62, 	issue: 2, 	pages: 369-370, 	date: 2020-06-01, 	doi: 10.1093/jcs/csaa012, 	language: eng, 	issn: 2040-4867, 	superior_ppn: 341338435, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Mark, 			last_name: Biondich, 			type: author, 		}, 	], 	keywords: [ Book Reviews ], } erased field '520a' due to removal filter '.' erased field '650a' due to removal filter '^((B\|b)ook (R\|r)eviews)\|((A\|a)rticles)$' Generated record with hash 'FD97C85F5B93844529092A02F1882BD8BC36B879'  Conversion complete   Generated 1 record(s) for item 1 [Journal of church an...] \| https://academic.oup.com/jcs/article/62/2/369/5814169?rss=1 {12736395429199931726}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1

**Comment by IxKo** [comment]
Wird nun als Rezension gekennzeichnet.
@kdr154 Es sind keine Issues zu der Zs mehr offen, es könnte getestet werden.
