### ISSUE TITLE
ISSN 1477-8556 | Journal of Semitic studies | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#995]
1. **URL**
https://academic.oup.com/jss/article/65/1/253/5738622?rss=1
IxTheo#2020-05-25#843FD586DA6D6C1E94959CA5255CB9F87AC2D4B1
**Ausführliche Problembeschreibung**
Rezensionen werden nur mit dem Keyword "Reviews" ausgezeichnet.
**Offenbare Lösungen**
In 655 als Rezensionen tagen.

2. **URL**
https://academic.oup.com/jss/article/65/1/271/5738641?rss=1
IxTheo#2020-05-25#96333B0370EDAA6848A4DB53C56E12745DC8EE5A
**Ausführliche Problembeschreibung**
Diese Rezension ist - im Gegensatz zu den anderen Rezensioen - unter der Rubrik "Short notes" und erhält das gleichnamige Keyword. Sollte jedoch als Rezension in 655 getagt werden.

**Comment by socheres** [comment]
Mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_RyW39F" "--output-filename=fy3kvB.xml"  "--config-overrides=remove_marc_field_650a    = "^Reviews?" zotero_review_regex       = "^Reviews?""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://academic.oup.com/jss/article/65/1/253/5738622?rss=1"  "Journal of Semitic studies"
-- | --
Runtime | 21s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of Semitic studies' \| DIRECT @ https://academic.oup.com/jss/article/65/1/253/5738622?rss=1 set download-delay for domain 'academic.oup.com' to 1000 ms   Harvesting URL 1 [Journal of Semitic s...] \| https://academic.oup.com/jss/article/65/1/253/5738622?rss=1 {16381115137755996910} Harvest successful     Converting item 1 [Journal of Semitic s...] \| https://academic.oup.com/jss/article/65/1/253/5738622?rss=1 {16381115137755996910} use online ISSN "1477-8556" with online PPN "341339423" post-processed author first name = 'Nathan', last name = 'Lovell', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://academic.oup.com/jss/article/65/1/253/5738622, 	item_type: review, 	title: A. Graeme Auld, Life In Kings: Reshaping the Royal Story in the Hebrew Bible, 	short_title: A. Graeme Auld, Life In Kings, 	abstract_note: Nathan Lovell; A. Graeme Auld, Life In Kings: Reshaping the Royal Story in the Hebrew Bible, Journal of Semitic Studies, Volume 65, Issue 1, 1 April 2020, Page, 	publication_title: Journal of Semitic Studies, 	volume: 65, 	issue: 1, 	pages: 253-255, 	date: 2020-04-01, 	doi: 10.1093/jss/fgz041, 	language: eng, 	issn: 1477-8556, 	superior_ppn: 341339423, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Nathan, 			last_name: Lovell, 			type: author, 		}, 	], 	keywords: [ Reviews ], } erased field '650a' due to removal filter '^Reviews?' Generated record with hash '831F007B18823D59BA388B0DE4BDBEDE057DD5C7'  Conversion complete   Generated 1 record(s) for item 1 [Journal of Semitic s...] \| https://academic.oup.com/jss/article/65/1/253/5738622?rss=1 {16381115137755996910}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1

**Comment by socheres** [comment]
auch Bsp. 2 getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_UUJUs1" "--output-filename=0azXtY.xml"  "--config-overrides=remove_marc_field_650a    = "(^Reviews?)\|(^Short  notes)" zotero_review_regex       = "(^Reviews?)\|(^Short notes)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://academic.oup.com/jss/article/65/1/271/5738641?rss=1"  "Journal of Semitic studies"
-- | --
Runtime | 16s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of Semitic studies' \| DIRECT @ https://academic.oup.com/jss/article/65/1/271/5738641?rss=1 set download-delay for domain 'academic.oup.com' to 1000 ms   Harvesting URL 1 [Journal of Semitic s...] \| https://academic.oup.com/jss/article/65/1/271/5738641?rss=1 {831108374023657984} Harvest successful     Converting item 1 [Journal of Semitic s...] \| https://academic.oup.com/jss/article/65/1/271/5738641?rss=1 {831108374023657984} use online ISSN "1477-8556" with online PPN "341339423" post-processed author first name = 'Charlotte', last name = 'Hempel', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://academic.oup.com/jss/article/65/1/271/5738641, 	item_type: review, 	title: Lena-Sofia Tiemeyer, Ezra-Nehemiah: Israel's Quest for Identity, 	short_title: Lena-Sofia Tiemeyer, Ezra-Nehemiah, 	abstract_note: Charlotte Hempel; Lena-Sofia Tiemeyer, Ezra-Nehemiah: Israel's Quest for Identity, Journal of Semitic Studies, Volume 65, Issue 1, 1 April 2020, Pages 271–272,, 	publication_title: Journal of Semitic Studies, 	volume: 65, 	issue: 1, 	pages: 271-272, 	date: 2020-04-01, 	doi: 10.1093/jss/fgz038, 	language: eng, 	issn: 1477-8556, 	superior_ppn: 341339423, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Charlotte, 			last_name: Hempel, 			type: author, 		}, 	], 	keywords: [ Short notes ], } erased field '650a' due to removal filter '(^Reviews?)\|(^Short notes)' Generated record with hash '6EA86F44CC72A5A76AA60BF2CE5F611EC66BAEBB'  Conversion complete   Generated 1 record(s) for item 1 [Journal of Semitic s...] \| https://academic.oup.com/jss/article/65/1/271/5738641?rss=1 {831108374023657984}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
